### ISSUE TITLE
Mobile Meta Tag

### ISSUE THREAD

**Issue by Mikeysax** [HortusHonu/splurty#1]
On mobile things don't look as good as they could be.
One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.
Let me know in the comments once you figured that step out :)

**Comment by HortusHonu** [comment]
I've updated my app with the mobile meta tag and it's working. I figured out how to do it via google :)

**Comment by Mikeysax** [comment]
Awesome 👍
